version: "3"
services:
    api:
      build: .
      container_name: api
      volumes:
        - ./:/app
      command: gunicorn --bind 0.0.0.0:5000 app:app
      ports:
        - "5000:5000"
    nginx:
      image: "nginx:latest"
      depends_on:
        - api
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
