version: "3"
services:
    api:
      build:
        context: ./api
        dockerfile: Dockerfile.api
      container_name: api
      depends_on:
        - redis
      volumes:
        - ./api:/app
      command: gunicorn --bind 0.0.0.0:5000 app:api.app
      ports:
        - "5000:5000"
    nginx:
      image: "nginx:latest"
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    redis:
      image: "redis:alpine"
